### ISSUE TITLE
Add issue and pr templates [.github]

### ISSUE THREAD

**Issue by JuaniBattiston** [Batucho/gifpy#3]
# Description
The proyect is missing any kind of guide on how to open an issue or contribute to the proyecy, any help with this would be great!

2 issue templates could be added, one for reporting bug, and another one to request features.

For bug report could be smt like this:

- Description:
- Steps to reproduce
- Posible solutions

Feature Request:

- Description
- Reason
- How would you implement it

**Comment by JuaniBattiston** [comment]
I'm planning to take this one unless someone wants to hop on it.

**Comment by dNhunter3107** [comment]
I would like to contribute

**Comment by JuaniBattiston** [comment]
Great! I'll assign it to you.
